apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-test
spec:
  replicas: 1
  selector:
    matchLabels:
     run: test
  template:
    metadata:
      labels:
        run: test
    spec:
      schedulerName: custom-scheduler
      containers:
      - name: test
        image: busybox:0.2
        command: ["sleep","3600"]
