apiVersion: apps/v1
kind: Deployment
metadata:
  name: custom-scheduler
  namespace: kube-system
  labels:
    component: custom-scheduler
spec:
  replicas: 1
  selector:
    matchLabels:
      component: custom-scheduler
  template:
    metadata:
      labels:
        component: custom-scheduler
    spec:
      serviceAccount: custom-scheduler-sa
      priorityClassName: system-cluster-critical
      volumes:
        - name: scheduler-config
          configMap:
            name: scheduler-config
      containers:
        - name: scheduler-ctrl
          image: IMAGE
          imagePullPolicy: Always
          args:
            - /scheduler-plugins
            - --config=/etc/kubernetes/scheduler-config.yaml
            - --leader-elect=false
            - --v=5
            - --scheduler-name=custom-scheduler
          volumeMounts:
            - name: scheduler-config
              mountPath: /etc/kubernetes
          resources:
            limits:
              cpu: "1"
              memory: 2Gi
